import { RewardCategory, RewardItem } from "./models";

/* ================= CATEGORIES ================= */

export const rewardCategories: RewardCategory[] = [
  {
    category_id: "ELEC",
    category_name: "Electronics",
    category_code: "ELEC",
    is_active: true,
  },
  {
    category_id: "FASH",
    category_name: "Fashion",
    category_code: "FASH",
    is_active: true,
  },
  {
    category_id: "FOOD",
    category_name: "Food",
    category_code: "FOOD",
    is_active: true,
  },
];

/* ================= ALL REWARDS ================= */

export const rewardItems: RewardItem[] = [
  /* ===== Coupons ===== */
  {
    id: "flipkart-1",
    title: "Flipkart Coupon",
    type: "coupon",
    category_ids: ["ELEC"],
    points_required: 15000,
    monetary_value: 2000,
    bgColor: "#BFF4BB",
    is_active: true,
  },
  {
    id: "amazon-1",
    title: "Amazon Coupon",
    type: "coupon",
    category_ids: ["ELEC"],
    points_required: 15000,
    monetary_value: 500,
    bgColor: "#EFB3CC",
    is_active: true,
  },
  {
    id: "flipkart-2",
    title: "Flipkart Coupon",
    type: "coupon",
    category_ids: ["ELEC"],
    points_required: 15000,
    monetary_value: 2000,
    bgColor: "#BFF4BB",
    is_active: true,
  },
  {
    id: "amazon-2",
    title: "Amazon Coupon",
    type: "coupon",
    category_ids: ["ELEC"],
    points_required: 15000,
    monetary_value: 500,
    bgColor: "#EFB3CC",
    is_active: true,
  },{
    id: "flipkart-3",
    title: "Flipkart Coupon",
    type: "coupon",
    category_ids: ["ELEC"],
    points_required: 15000,
    monetary_value: 2000,
    bgColor: "#BFF4BB",
    is_active: true,
  },
  {
    id: "amazon-3",
    title: "Amazon Coupon",
    type: "coupon",
    category_ids: ["ELEC"],
    points_required: 15000,
    monetary_value: 500,
    bgColor: "#EFB3CC",
    is_active: true,
  },
  

  /* ===== Products ===== */
  {
    id: "iphone16",
    title: "iPhone 16 Pro",
    type: "product",
    category_ids: ["ELEC"],
    points_required: 50000,
    monetary_value: 79990,
    image: "/images/Iphone.png",
    is_active: true,
    is_out_of_stock: false,
  },
  {
    id: "nike-air",
    title: "Nike Air Max Sneakers",
    type: "product",
    category_ids: ["FASH"],
    points_required: 25000,
    monetary_value: 12999,
    image: "/images/nike.png",
    is_active: true,
    is_out_of_stock: false,
  },
  {
    id: "swiggy-1",
    title: "Swiggy Premium Voucher",
    type: "product",
    category_ids: ["FOOD"],
    points_required: 8000,
    monetary_value: 1000,
    image: "/images/swiggy.png",
    is_active: true,
    is_out_of_stock: true,
  },
  {
    id: "swiggy-2",
    title: "Swiggy Premium Voucher",
    type: "product",
    category_ids: ["FOOD"],
    points_required: 8000,
    monetary_value: 2000,
    image: "/images/swiggy.png",
    is_active: true,
    is_out_of_stock: false,
  },
{
    id: "swiggy-3",
    title: "Swiggy Premium Voucher",
    type: "product",
    category_ids: ["FOOD"],
    points_required: 8000,
    monetary_value: 5000,
    image: "/images/swiggy.png",
    is_active: true,
    is_out_of_stock: false,
  },
  {
    id: "swiggy-4",
    title: "Swiggy Premium Voucher",
    type: "product",
    category_ids: ["FOOD"],
    points_required: 8000,
    monetary_value: 7000,
    image: "/images/swiggy.png",
    is_active: true,
    is_out_of_stock: false,
  },
];